pipeline {
    agent any

    stages {
        stage('git clone frontend') {
            steps {
                git branch: 'client', url: 'https://github.com/AhTheary/vue.git'
                
            }
        }
        stage('build frontend') {
            steps {
                sh 'pwd'
                sh 'npm -v'
                sh 'cd /var/lib/jenkins/workspace/devops/client && npm install && pwd && npm run build '
                sh 'pwd'
            }
        }
 
        // stage('build backend') {
        //     steps {
        //         sh 'pwd'
        //         sh 'npm -v'
        //         sh 'cd /var/lib/jenkins/workspace/npm/server && npm install && pwd && npm run build '
        //         sh 'pwd'
        //     }
        // }
    }
}
